#ifndef WEBSERVER_H
#define WEBSERVER_H

// HTML-sivu BLE-skannerin web-käyttöliittymälle
const char HTML_PAGE[] = 
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1.0'>"
"<meta name='theme-color' content='#0f172a'>"
"<link rel='manifest' href='/manifest.json'>"
"<link rel='icon' type='image/png' sizes='192x192' href='/icon-192.png'>"
"<link rel='apple-touch-icon' sizes='192x192' href='/icon-192.png'>"
"<title>BLE Laitteet</title>"
"<script src='https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js'></script>"
"<script src='https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@3.0.0/dist/chartjs-adapter-date-fns.bundle.min.js'></script>"
"<script>if('serviceWorker' in navigator){window.addEventListener('load',()=>{navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).then(r=>{r.update();}).catch(()=>{});});}</script>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
"background:#0f172a;min-height:100vh;padding:20px;color:#e2e8f0}"
".container{max-width:1000px;margin:0 auto}"
".header{display:flex;justify-content:space-between;align-items:center;margin-bottom:32px;"
"padding:24px;background:linear-gradient(135deg,#1e293b 0%,#334155 100%);"
"border-radius:16px;box-shadow:0 4px 24px rgba(0,0,0,0.4)}"
"h1{color:#f1f5f9;font-size:28px;margin:0;font-weight:700;letter-spacing:-0.5px;"
"display:flex;align-items:center;gap:12px}"
"h1::before{content:'📡';font-size:32px}"
".toggle-btn{background:#334155;color:#e2e8f0;border:1px solid #475569;"
"padding:10px 20px;border-radius:8px;cursor:pointer;font-size:14px;font-weight:600;"
"transition:all 0.2s;box-shadow:0 2px 8px rgba(0,0,0,0.2)}"
".toggle-btn:hover{background:#475569;border-color:#64748b;transform:translateY(-1px);"
"box-shadow:0 4px 12px rgba(0,0,0,0.3)}"
".toggle-btn.active{background:#3b82f6;border-color:#3b82f6;color:white}"
".toggle-btn.icon-btn{padding:8px;width:36px;height:36px;display:inline-flex;align-items:center;justify-content:center;font-size:18px}"
".time-btn{background:#334155;color:#e2e8f0;border:1px solid #475569;"
"padding:8px 16px;border-radius:6px;cursor:pointer;font-size:13px;font-weight:600;"
"transition:all 0.2s;flex:1}"
".time-btn:hover{background:#475569;border-color:#64748b}"
".time-btn.active{background:#3b82f6;border-color:#3b82f6;color:white}"
".device-card{background:#1e293b;border:1px solid #334155;border-radius:12px;padding:24px;"
"margin-bottom:16px;box-shadow:0 2px 16px rgba(0,0,0,0.3);position:relative;transition:all 0.2s;z-index:1}"
".device-card.settings-open{z-index:100}"
".device-card:hover{border-color:#475569;box-shadow:0 4px 24px rgba(0,0,0,0.4);transform:translateY(-2px)}"
".device-card.unsaved{border:2px dashed #10b981;background:#0a3428}"
".device-card.unsaved .device-name::after{content:' (ei tallennettu)';font-size:12px;color:#10b981;font-weight:400}"
".device-header{display:flex;justify-content:space-between;align-items:flex-start}"
".device-info{flex:1}"
".device-name{font-size:18px;font-weight:700;color:#f1f5f9;margin-bottom:6px;letter-spacing:-0.3px}"
".device-mac{font-family:'JetBrains Mono','Courier New',monospace;font-size:12px;color:#64748b;"
"background:#0f172a;padding:4px 8px;border-radius:4px;display:inline-block;margin-top:4px}"
".settings-icon{background:none;border:none;font-size:24px;cursor:pointer;padding:8px;"
"color:#64748b;transition:all 0.2s;border-radius:8px}"
".settings-icon:hover{color:#e2e8f0;background:#334155;transform:rotate(90deg)}"
".settings-panel{display:none;position:absolute;right:16px;top:60px;background:#1e293b;"
"border:1px solid #334155;border-radius:12px;box-shadow:0 8px 32px rgba(0,0,0,0.5);"
"min-width:240px;z-index:9999}"
".settings-panel.open{display:block}"
".settings-option{padding:12px 16px;cursor:pointer;transition:background 0.2s;"
"border-bottom:1px solid #334155;color:#e2e8f0}"
".settings-option:last-child{border-bottom:none}"
".settings-option:hover{background:#334155}"
".settings-option.danger{color:#f87171}"
".settings-option.danger:hover{background:#450a0a;color:#fca5a5}"
".danger-btn{background:#dc2626;color:white;border:none;padding:10px 14px;border-radius:8px;cursor:pointer;font-weight:700;transition:all 0.2s}"
".danger-btn:hover{background:#b91c1c;transform:translateY(-1px)}"
".sensor-data{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));"
"gap:16px;margin-top:20px;padding-top:20px;border-top:1px solid #334155}"
".sensor-value{text-align:center;background:#0f172a;padding:16px;border-radius:8px;"
"border:1px solid #1e293b;transition:all 0.2s}"
".sensor-value:hover{border-color:#334155;transform:translateY(-2px)}"
".sensor-value.primary{grid-column:span 1;background:linear-gradient(135deg,#1e293b,#334155);"
"border:2px solid #3b82f6;padding:20px}"
".sensor-label{font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:0.8px;"
"margin-bottom:8px;font-weight:600}"
".sensor-value.primary .sensor-label{font-size:12px;color:#60a5fa;font-weight:700}"
".sensor-number{font-size:26px;font-weight:700;color:#3b82f6}"
".sensor-value.primary .sensor-number{font-size:42px;color:#60a5fa;text-shadow:0 0 20px rgba(96,165,250,0.3)}"
".sensor-unit{font-size:13px;color:#64748b;margin-left:2px;font-weight:500}"
".sensor-value.primary .sensor-unit{font-size:18px;color:#93c5fd}"
".temp-cold{color:#60a5fa !important}"
".temp-cool{color:#34d399 !important}"
".temp-normal{color:#fbbf24 !important}"
".temp-warm{color:#fb923c !important}"
".temp-hot{color:#f87171 !important}"
".battery-container{display:flex;flex-direction:column;align-items:center;gap:8px}"
".battery-bar{width:80px;height:22px;border:2px solid #475569;border-radius:6px;position:relative;"
"background:#0f172a;overflow:hidden}"
".battery-bar::after{content:'';position:absolute;top:50%;right:-7px;transform:translateY(-50%);"
"width:4px;height:12px;background:#475569;border-radius:0 3px 3px 0}"
".battery-fill{height:100%;border-radius:3px;transition:width 0.3s,background 0.3s}"
".battery-fill.high{background:linear-gradient(90deg,#10b981,#34d399)}"
".battery-fill.medium{background:linear-gradient(90deg,#f59e0b,#fbbf24)}"
".battery-fill.low{background:linear-gradient(90deg,#ef4444,#f87171)}"
".signal-container{display:flex;align-items:center;gap:8px;justify-content:center}"
".signal-bars{display:flex;align-items:flex-end;gap:3px;height:20px}"
".signal-bar{width:5px;border-radius:2px;transition:background 0.3s}"
".signal-bar:nth-child(1){height:25%}"
".signal-bar:nth-child(2){height:50%}"
".signal-bar:nth-child(3){height:75%}"
".signal-bar:nth-child(4){height:100%}"
".signal-bar.active.excellent,.signal-bar.active.good{background:#10b981}"
".signal-bar.active.fair{background:#f59e0b}"
".signal-bar.active.poor{background:#ef4444}"
".signal-bar.inactive{background:#334155}"
".rssi{display:inline-block;margin-top:12px;padding:6px 12px;background:#0f172a;"
"border-radius:6px;font-size:12px;color:#94a3b8;border:1px solid #1e293b}"
".simple-list{background:#0f172a;border:1px solid #334155;border-radius:12px;overflow:hidden}"
".simple-list-header,.simple-row{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:8px;padding:10px 12px;align-items:center}"
".simple-list-header{background:#1e293b;color:#cbd5f5;font-weight:700;font-size:12px;text-transform:uppercase;letter-spacing:0.5px}"
".simple-row{border-top:1px solid #1f2937;font-size:14px}"
".simple-row:nth-child(even){background:#111827}"
".simple-icon{font-size:12px;margin-right:6px;opacity:0.85}"
".simple-name{font-weight:600;color:#e2e8f0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
".simple-temp{font-weight:700;color:#60a5fa}"
".simple-hum{color:#a7f3d0;font-weight:600}"
".simple-age{color:#94a3b8;font-family:'JetBrains Mono','Courier New',monospace;font-size:12px}"
".chart-container{margin-top:20px;padding-top:20px;border-top:1px solid #334155;height:200px;position:relative}"
".chart-container canvas{max-height:180px}"
".no-devices{text-align:center;padding:60px 20px;color:#64748b;font-size:18px;font-weight:500}"
".modal{display:none;position:fixed;z-index:1000;left:0;top:0;width:100%;height:100%;"
"background:rgba(0,0,0,0.8);backdrop-filter:blur(4px)}"
".modal.show{display:flex;align-items:center;justify-content:center}"
".modal-content{background:#1e293b;border-radius:16px;max-width:800px;width:90%;"
"max-height:80vh;overflow-y:auto;box-shadow:0 20px 60px rgba(0,0,0,0.6);"
"border:1px solid #334155}"
".modal-header{padding:24px;border-bottom:1px solid #334155;display:flex;"
"justify-content:space-between;align-items:center}"
".modal-header h2{color:#f1f5f9;font-size:24px;margin:0}"
".modal-close{background:none;border:none;font-size:32px;color:#64748b;"
"cursor:pointer;padding:0;width:40px;height:40px;border-radius:8px;"
"transition:all 0.2s}"
".modal-close:hover{background:#334155;color:#f1f5f9}"
".modal-body{padding:24px}"
".discovery-device{background:#0f172a;border:1px solid #334155;border-radius:12px;"
"padding:20px;margin-bottom:12px;display:flex;justify-content:space-between;"
"align-items:center;transition:all 0.2s}"
".discovery-device:hover{border-color:#475569;background:#1a1f2e}"
".discovery-info h3{color:#f1f5f9;font-size:16px;margin-bottom:4px}"
".discovery-info p{color:#64748b;font-size:13px}"
".add-btn{background:#10b981;color:white;border:none;padding:10px 20px;"
"border-radius:8px;cursor:pointer;font-weight:600;transition:all 0.2s}"
".add-btn:hover{background:#059669;transform:translateY(-1px)}"
".add-btn:disabled{background:#334155;color:#64748b;cursor:not-allowed;transform:none}"
".settings-tabs{display:flex;gap:8px;padding:0 24px;border-bottom:1px solid #334155}"
".settings-tab-btn{background:none;border:none;padding:14px 20px;color:#94a3b8;"
"cursor:pointer;font-weight:600;font-size:14px;border-bottom:3px solid transparent;"
"transition:all 0.2s}"
".settings-tab-btn:hover{color:#e2e8f0;background:rgba(255,255,255,0.05)}"
".settings-tab-btn.active{color:#60a5fa;border-bottom-color:#60a5fa}"
".settings-tab-content{display:none;padding:24px}"
".settings-tab-content.active{display:block}"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<div class='header'>"
"<h1>BLE-laitteet</h1>"
"<div id='deviceStats' style='font-size:13px;color:#94a3b8;margin-top:4px;'></div>"
"<div style='display:flex;gap:12px;'>"
"<button class='toggle-btn icon-btn' id='scanBtn' onclick='openDiscovery()' title='Löydä laitteita'>🔍</button>"
"<button class='toggle-btn icon-btn' onclick='openSettings()' title='Asetukset'>⚙️</button>"
"<button class='toggle-btn icon-btn' id='simpleViewBtn' onclick='toggleSimpleView()' title='Tiivis lista'>📋</button>"
"</div>"
"</div>"
"<div id='devices'></div>"
"</div>"
"<div id='discoveryModal' class='modal'>"
"<div class='modal-content'>"
"<div class='modal-header'>"
"<h2>🔍 Löydetyt laitteet</h2>"
"<button class='modal-close' onclick='closeDiscovery()'>×</button>"
"</div>"
"<div class='modal-body'>"
"<div style='display:flex;justify-content:flex-end;margin-bottom:12px;'>"
"<button class='danger-btn' onclick='clearAllSelections()'>🗑️ Poista kaikki valinnat</button>"
"</div>"
"<div id='discoveryDevices'></div>"
"</div>"
"</div>"
"</div>"
"<script>"
"let openDeviceSettings=null;"
"let simpleView=localStorage.getItem('simpleView')==='1';"
"function applySimpleView(){"
"const btn=document.getElementById('simpleViewBtn');"
"if(simpleView){document.body.classList.add('simple-view');btn.classList.add('active');}"
"else{document.body.classList.remove('simple-view');btn.classList.remove('active');}"
"localStorage.setItem('simpleView',simpleView?'1':'0');}"
"function toggleSimpleView(){simpleView=!simpleView;applySimpleView();updateDevices();}"
"let scanCountdown=0;"
"let scanInterval=null;"
"let discoveryInterval=null;"
"applySimpleView();"
"async function openDiscovery(){"
"document.getElementById('discoveryModal').classList.add('show');"
"await startScan();"
"updateDiscoveryDevices();"
"discoveryInterval=setInterval(updateDiscoveryDevices,2000);}"
"async function closeDiscovery(){"
"document.getElementById('discoveryModal').classList.remove('show');"
"if(discoveryInterval){clearInterval(discoveryInterval);discoveryInterval=null;}"
"await fetch('/api/stop-scan',{method:'POST'});}"
"async function startScan(){"
"try{"
"const resp=await fetch('/api/start-scan',{method:'POST'});"
"const result=await resp.json();"
"if(!result.ok){"
"alert('Skannauksen käynnistys epäonnistui');}"
"}catch(e){alert('Virhe: '+e.message);}}"
"async function updateDiscoveryDevices(){"
"try{"
"const res=await fetch('/api/devices?all=1');"
"const data=await res.json();"
"const container=document.getElementById('discoveryDevices');"
"if(data.length===0){container.innerHTML='<div class=\"no-devices\">Ei löydetty laitteita</div>';return;}"
"let html='';"
"data.forEach(d=>{"
"const name=d.name||'Nimetön laite';"
"const addr=d.addr;"
"const sourceLabel=(d.source&&d.source!==''&&d.source!=='local')?('Satelliitti '+d.source.replace('satellite-','')):'Master';"
"const isAdded=d.saved;"
"html+='<div class=\"discovery-device\">';"
"html+='<div class=\"discovery-info\">';"
"html+='<h3>'+name+'</h3>';"
"html+='<p>'+addr+' • '+sourceLabel;"
"if(d.hasSensor)html+=' • 🌡️ '+d.temp.toFixed(1)+'°C • 💧 '+d.hum+'%';"
"html+='</p></div>';"
"if(isAdded){"
"html+='<button class=\"add-btn\" disabled>✓ Lisätty</button>';"
"}else{"
"html+='<button class=\"add-btn\" onclick=\"addToMain(\\''+addr+'\\');\">+ Lisää</button>';}"
"html+='</div>';});"
"container.innerHTML=html;"
"}catch(err){console.error('Virhe:',err);}}"
"async function addToMain(addr){"
"try{"
"const resp=await fetch('/api/toggle-visibility',{method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:'addr='+encodeURIComponent(addr)+'&visible=1'});"
"const result=await resp.json();"
"if(result.ok){"
"updateDiscoveryDevices();"
"updateDevices();"
"}else{alert('Virhe lisäyksessä');}"
"}catch(err){console.error('Virhe:',err);}}"
"async function clearAllSelections(){"
"if(!confirm('Poistetaanko kaikki valinnat päänäkymästä?'))return;"
"try{"
"const resp=await fetch('/api/clear-visibility',{method:'POST'});"
"const result=await resp.json();"
"if(result.ok){"
"updateDiscoveryDevices();"
"updateDevices();"
"}else{alert('Virhe: valintojen poisto epäonnistui');}"
"}catch(err){console.error('Virhe:',err);alert('Virhe: valintojen poisto epäonnistui');}}"
"function toggleSettings(addr){"
"const panel=document.getElementById('settings-'+addr);"
"const card=panel?panel.closest('.device-card'):null;"
"if(openDeviceSettings&&openDeviceSettings!==panel){"
"openDeviceSettings.classList.remove('open');"
"const oldCard=openDeviceSettings.closest('.device-card');"
"if(oldCard)oldCard.classList.remove('settings-open');}"
"if(panel){"
"panel.classList.toggle('open');"
"const isOpen=panel.classList.contains('open');"
"openDeviceSettings=isOpen?panel:null;"
"if(card)card.classList.toggle('settings-open',isOpen);}}"
"document.addEventListener('click',(e)=>{"
"if(!e.target.closest('.settings-icon')&&!e.target.closest('.settings-panel')){"
"if(openDeviceSettings){"
"openDeviceSettings.classList.remove('open');"
"const card=openDeviceSettings.closest('.device-card');"
"if(card)card.classList.remove('settings-open');"
"openDeviceSettings=null;}}});"
"async function hideDevice(addr,event){"
"if(event){event.stopPropagation();}"
"console.log('Poistetaan laite päänäkymästä:',addr);"
"if(openDeviceSettings){openDeviceSettings.classList.remove('open');openDeviceSettings=null;}"
"try{"
"const resp=await fetch('/api/toggle-visibility',{method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:'addr='+encodeURIComponent(addr)+'&visible=0'});"
"const result=await resp.json();"
"console.log('Vastaus:',result);"
"setTimeout(updateDevices,100);"
"}catch(err){console.error('Virhe:',err);}}"
"async function showDevice(addr,event){"
"if(event){event.stopPropagation();}"
"console.log('Lisätään laite päänäkymään:',addr);"
"if(openDeviceSettings){openDeviceSettings.classList.remove('open');openDeviceSettings=null;}"
"try{"
"const resp=await fetch('/api/toggle-visibility',{method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:'addr='+encodeURIComponent(addr)+'&visible=1'});"
"const result=await resp.json();"
"console.log('Vastaus:',result);"
"setTimeout(updateDevices,100);"
"}catch(err){console.error('Virhe:',err);}}"
"async function saveSettings(addr,addrClean,applyToSimilar,event){"
"if(event){event.stopPropagation();}"
"const name=document.getElementById('name-'+addrClean).value;"
"const showMac=document.getElementById('showmac-'+addrClean).checked?1:0;"
"const showIp=document.getElementById('showip-'+addrClean).checked?1:0;"
"let fieldMask=0;"
"document.querySelectorAll('#settings-'+addrClean+' .field-check').forEach(cb=>{"
"if(cb.checked){fieldMask|=parseInt(cb.getAttribute('data-bit'));}});"
"console.log('Tallennetaan:',addr,'name=',name,'showMac=',showMac,'fields=',fieldMask,'apply=',applyToSimilar);"
"try{"
"const resp=await fetch('/api/update-settings',{method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:'addr='+encodeURIComponent(addr)+'&name='+encodeURIComponent(name)+'&show_mac='+showMac+'&show_ip='+showIp+'&field_mask='+fieldMask+'&apply_to_similar='+(applyToSimilar?1:0)});"
"const result=await resp.json();"
"console.log('Vastaus:',result);"
"if(result.updated>1){"
"alert('Asetukset tallennettu '+result.updated+' laitteelle!');"
"}else{"
"alert('Asetukset tallennettu!');}"
"if(openDeviceSettings){openDeviceSettings.classList.remove('open');openDeviceSettings=null;}"
"setTimeout(updateDevices,100);"
"}catch(err){console.error('Virhe:',err);alert('Virhe tallennettaessa!');}}"
"async function updateDevices(){"
"if(openDeviceSettings){console.log('Asetukset auki, ohitetaan päivitys');return;}"
"try{"
"const url='/api/devices';"
"const res=await fetch(url);"
"const data=await res.json();"
"console.log('Löydetty',data.length,'laitetta');"
"let masterCount=0;let satCount=0;"
"data.forEach(d=>{if(d.source&&d.source!=='local'&&d.source!==''){satCount++;}else{masterCount++;}});"
"const statsDiv=document.getElementById('deviceStats');"
"if(statsDiv){statsDiv.innerHTML='Master: '+masterCount+' | 📡 Satelliitit: '+satCount;}"
"if(data.length===0){document.getElementById('devices').innerHTML="
"'<div class=\"no-devices\">Ei näytettäviä laitteita</div>';return;}"
"if(simpleView){"
"let html='<div class=\"simple-list\">'"
"+'<div class=\"simple-list-header\">'"
"+'<div><span class=\"simple-icon\">🏷️</span>Nimi</div>'"
"+'<div><span class=\"simple-icon\">📡</span>Lähde</div>'"
"+'<div><span class=\"simple-icon\">🌡️</span>Lämpö</div>'"
"+'<div><span class=\"simple-icon\">💧</span>Kosteus</div>'"
"+'<div><span class=\"simple-icon\">⏱️</span>Päivitys</div>'"
"+'</div>';"
"data.forEach(d=>{"
"const name=d.name||'Nimetön laite';"
"let tempText='--';"
"let tempClass='temp-normal';"
"if((d.fieldMask&1)&&typeof d.temp==='number'){"
"const t=d.temp;"
"tempText=t.toFixed(1)+'°C';"
"if(t<10)tempClass='temp-cold';"
"else if(t<18)tempClass='temp-cool';"
"else if(t>30)tempClass='temp-hot';"
"else if(t>26)tempClass='temp-warm';}"
"let humText='--';"
"if((d.fieldMask&2)&&typeof d.hum==='number'){humText=d.hum+'%';}"
"const age=(typeof d.ageSec==='number')?d.ageSec:0;"
"const sourceLabel=(d.source&&d.source!==''&&d.source!=='local')?('Sat '+d.source.replace('satellite-','')):'Master';"
"html+='<div class=\"simple-row\">'"
"+'<div class=\"simple-name\">'+name+'</div>'"
"+'<div class=\"simple-source\">'+sourceLabel+'</div>'"
"+'<div class=\"simple-temp '+tempClass+'\">'+tempText+'</div>'"
"+'<div class=\"simple-hum\">'+humText+'</div>'"
"+'<div class=\"simple-age\">'+age+'s</div>'"
"+'</div>';});"
"html+='</div>';"
"const devicesDiv=document.getElementById('devices');"
"if(devicesDiv.innerHTML!==html){devicesDiv.innerHTML=html;}"
"return;}"
"let html='';"
"data.forEach(d=>{"
"const name=d.name||'Nimetön laite';"
"const advName=d.advName||'';"
"const sourceLabel=(d.source&&d.source!==''&&d.source!=='local')?('Satelliitti '+d.source.replace('satellite-','')):'Master';"
"const addrClean=d.addr.replace(/:/g,'');"
"const savedClass=d.saved?'':'unsaved';"
"html+='<div class=\"device-card '+savedClass+'\">'"
"+' <div class=\"device-header\">'"
"+' <div class=\"device-info\">'"
"+' <div class=\"device-name\">';"
"if(d.source&&d.source!=='local'&&d.source!==''){const satName=d.source.replace('satellite-','');html+='<span style=\"margin-right:6px;\" title=\"Satelliitti: '+satName+'\">📡</span>';}"
"html+=name;"
"if(d.showIp&&d.source&&d.source.startsWith('satellite-')){"
"const satIP=d.source.replace('satellite-','');"
"html+=' <span style=\"display:inline-block;margin-left:8px;padding:2px 8px;background:#6366f1;color:white;border-radius:4px;font-size:11px;font-weight:600;vertical-align:middle;\">🛰️ '+satIP+'</span>'; }"
"if(d.firmware&&d.firmware!=='Unknown'){"
"html+=' <span style=\"display:inline-block;margin-left:8px;padding:2px 8px;background:#3b82f6;color:white;border-radius:4px;font-size:11px;font-weight:600;vertical-align:middle;\">'+d.firmware+'</span>';}"
"html+='</div>';"
"if(d.showMac){"
"html+=' <div class=\"device-mac\">'+d.addr+'</div>';}"
"html+=' <div style=\"font-size:12px;color:#94a3b8;margin-top:2px;\">Lähde: '+sourceLabel+'</div>';"
"html+=' </div>'"
"+' <div style=\"display:flex;gap:6px;\">';"
"if(d.hasSensor&&(d.fieldMask&1)){"
"html+=' <button onclick=\"openChart(\\''+name.replace(/'/g,'\\\\\\'')+'\\',\\''+d.addr+'\\')\" style=\"padding:6px 10px;background:#3b82f6;color:white;border:none;border-radius:6px;cursor:pointer;font-size:18px;line-height:1;\" title=\"Näytä lämpötilahistoria\">📊</button>';}"
"html+=' <button class=\"settings-icon\" onclick=\"toggleSettings(\\''+addrClean+'\\')\" >⚙️</button>'"
"+' </div>'"
"+' <div class=\"settings-panel\" id=\"settings-'+addrClean+'\">';"
"html+=' <div style=\"padding:14px;\">'"
"+' <label style=\"display:block;margin-bottom:6px;font-weight:600;color:#f1f5f9;font-size:13px;\">Nimi:</label>'"
"+' <input type=\"text\" id=\"name-'+addrClean+'\" value=\"'+name+'\" style=\"width:100%;padding:8px;margin-bottom:12px;border:1px solid #475569;border-radius:6px;background:#0f172a;color:#e2e8f0;font-size:14px;\" />'"
"+' <label style=\"display:block;margin-bottom:6px;font-weight:600;color:#f1f5f9;font-size:13px;\">Mainosnimi:</label>'"
"+' <input type=\"text\" value=\"'+advName+'\" readonly style=\"width:100%;padding:8px;margin-bottom:12px;border:1px solid #475569;border-radius:6px;background:#0f172a;color:#94a3b8;font-size:13px;\" />'"
"+' <label style=\"display:flex;align-items:center;margin-bottom:12px;color:#e2e8f0;cursor:pointer;\">'"
"+' <input type=\"checkbox\" id=\"showmac-'+addrClean+'\" '+(d.showMac?'checked':'')+' style=\"margin-right:8px;cursor:pointer;\" />'"
"+' <span style=\"font-size:13px;\">Näytä MAC-osoite</span>'"
"+' </label>'"
"+' <label style=\"display:flex;align-items:center;margin-bottom:12px;color:#e2e8f0;cursor:pointer;\">'"
"+' <input type=\"checkbox\" id=\"showip-'+addrClean+'\" '+(d.showIp?'checked':'')+' style=\"margin-right:8px;cursor:pointer;\" />'"
"+' <span style=\"font-size:13px;\">Näytä satelliitti-IP</span>'"
"+' </label>'"
"+' <div style=\"margin-bottom:10px;font-weight:600;color:#f1f5f9;font-size:13px;\">Näytettävät kentät:</div>';"
"const fields=[{bit:1,label:'Lämpötila'},{bit:2,label:'Kosteus'},{bit:4,label:'Akku %'},{bit:8,label:'Jännite'},{bit:16,label:'Signaali'}];"
"fields.forEach(f=>{"
"const available=(d.availableFields&f.bit)!==0;"
"const checked=(d.fieldMask&f.bit)!==0;"
"if(available){"
"html+=' <label style=\"display:flex;align-items:center;margin-bottom:6px;color:#e2e8f0;cursor:pointer;\">'"
"+' <input type=\"checkbox\" class=\"field-check\" data-bit=\"'+f.bit+'\" '+(checked?'checked':'')+' style=\"margin-right:8px;cursor:pointer;\" />'"
"+' <span style=\"font-size:13px;\">'+f.label+'</span> </label>';}});"
"html+=' <button onclick=\"saveSettings(\\''+d.addr+'\\',\\''+addrClean+'\\',false,event)\" style=\"width:100%;padding:10px;margin-top:14px;background:#3b82f6;color:white;border:none;border-radius:6px;cursor:pointer;font-weight:600;font-size:13px;transition:background 0.2s;\" onmouseover=\"this.style.background=\\'#2563eb\\'\" onmouseout=\"this.style.background=\\'#3b82f6\\'\">💾 Tallenna</button>'"
"+' <button onclick=\"saveSettings(\\''+d.addr+'\\',\\''+addrClean+'\\',true,event)\" style=\"width:100%;padding:10px;margin-top:6px;background:#10b981;color:white;border:none;border-radius:6px;cursor:pointer;font-weight:600;font-size:13px;transition:background 0.2s;\" onmouseover=\"this.style.background=\\'#059669\\'\" onmouseout=\"this.style.background=\\'#10b981\\'\">🔁 Sovella samanlaisiin</button>';"
"if(d.saved){"
"html+=' <div class=\"settings-option danger\" onclick=\"hideDevice(\\''+d.addr+'\\',event)\" style=\"margin-top:10px;\">➖ Poista päänäkymästä</div>';"
"}else{"
"html+=' <div class=\"settings-option\" onclick=\"showDevice(\\''+d.addr+'\\',event)\" style=\"margin-top:10px;background:#10b981;\">💾 Tallenna päänäkymään</div>';}"
"html+=' </div></div>'"
"+' </div>';"
"if(d.hasSensor){"
"html+=' <div class=\"sensor-data\">';"
"if((d.fieldMask&1)&&d.temp){"
"let tempClass='temp-normal';"
"if(d.temp<10)tempClass='temp-cold';"
"else if(d.temp<18)tempClass='temp-cool';"
"else if(d.temp>26)tempClass='temp-warm';"
"else if(d.temp>30)tempClass='temp-hot';"
"html+=' <div class=\"sensor-value primary\">'"
"+' <div class=\"sensor-label\">🌡️ Lämpötila</div>'"
"+' <div class=\"sensor-number '+tempClass+'\">'+d.temp.toFixed(1)+'<span class=\"sensor-unit\">°C</span></div>'"
"+' </div>';}"
"if((d.fieldMask&2)&&d.hum){"
"html+=' <div class=\"sensor-value\">'"
"+' <div class=\"sensor-label\">💧 Kosteus</div>'"
"+' <div class=\"sensor-number\">'+d.hum+'<span class=\"sensor-unit\">%</span></div>'"
"+' </div>';}"
"if((d.fieldMask&4)&&d.bat){"
"const batClass=d.bat>50?'high':(d.bat>20?'medium':'low');"
"html+=' <div class=\"sensor-value\">'"
"+' <div class=\"sensor-label\">🔋 Akku</div>'"
"+' <div class=\"battery-container\">'"
"+' <div class=\"battery-bar\"><div class=\"battery-fill '+batClass+'\" style=\"width:'+d.bat+'%\"></div></div>'"
"+' <div class=\"sensor-number\" style=\"font-size:18px;\">'+d.bat+'%</div>'"
"+' </div>'"
"+' </div>';}"
"if((d.fieldMask&8)&&d.batMv){"
"html+=' <div class=\"sensor-value\">'"
"+' <div class=\"sensor-label\">⚡ Jännite</div>'"
"+' <div class=\"sensor-number\">'+d.batMv+'<span class=\"sensor-unit\">mV</span></div>'"
"+' </div>';}"
"html+=' </div>';}"
"if(d.fieldMask&16){"
"let barCount=0,signalClass='';"
"if(d.rssi>=-50){barCount=4;signalClass='excellent';}"
"else if(d.rssi>=-65){barCount=3;signalClass='good';}"
"else if(d.rssi>=-75){barCount=2;signalClass='fair';}"
"else{barCount=1;signalClass='poor';}"
"html+=' <div class=\"rssi\"><div class=\"signal-container\">'"
"+' <div class=\"signal-bars\">';"
"for(let i=1;i<=4;i++){"
"html+='<div class=\"signal-bar '+(i<=barCount?'active '+signalClass:'inactive')+'\"></div>';}"
"html+=' </div><span style=\"font-size:13px;color:#7f8c8d;\">'+d.rssi+' dBm</span></div></div>';}"
"html+='</div>';});"
"const devicesDiv=document.getElementById('devices');"
"if(devicesDiv.innerHTML!==html){"
"devicesDiv.innerHTML=html;}"
"}catch(error){console.error('Virhe haettaessa laitteita:',error);}}"
"let currentChart=null;"
"let currentChartName='';"
"let currentChartAddr='';"
"async function openChart(name,addr,hours=24){"
"currentChartName=name;currentChartAddr=addr;"
"document.getElementById('chartModal').classList.add('show');"
"document.querySelectorAll('.time-btn').forEach(b=>b.classList.remove('active'));"
"document.querySelector(`.time-btn[data-hours='${hours}']`)?.classList.add('active');"
"let title='📊 '+name+' - ';"
"if(hours===1)title+='Viimeinen tunti';"
"else if(hours===24)title+='Viimeinen vuorokausi';"
"else if(hours===168)title+='Viimeinen viikko';"
"else title+='Viimeinen kuukausi';"
"document.getElementById('chartTitle').textContent=title;"
"if(currentChart){try{currentChart.destroy();}catch(e){}currentChart=null;}"
"const canvas=document.getElementById('chartCanvas');"
"const ctx=canvas.getContext('2d');"
"try{"
"const r=await fetch('/api/aio/config');"
"const cfg=await r.json();"
"if(!cfg.ok||!cfg.has_key||!cfg.key){alert('Adafruit IO ei konfiguroitu');return;}"
"const cleanName=name.toLowerCase().replace(/[^a-z0-9]+/g,'-');"
"const macClean=addr.replace(/:/g,'').toLowerCase();"
"const feedName=cleanName+'-'+macClean.slice(-4)+'-temp';"
"const url=`https://io.adafruit.com/api/v2/${cfg.username}/feeds/${feedName}/data?start_time=${new Date(Date.now()-hours*3600*1000).toISOString()}`;"
"const res=await fetch(url,{headers:{'X-AIO-Key':cfg.key}});"
"if(!res.ok){alert('Ei dataa saatavilla');return;}"
"const data=await res.json();"
"const temps=data.reverse().map(d=>({x:new Date(d.created_at),y:parseFloat(d.value)}));"
"let timeUnit='hour',displayFormat='HH:mm';"
"if(hours<=1){timeUnit='minute';displayFormat='HH:mm';}"
"else if(hours<=24){timeUnit='hour';displayFormat='HH:mm';}"
"else if(hours<=168){timeUnit='day';displayFormat='dd.MM';}"
"else{timeUnit='day';displayFormat='dd.MM';}"
"currentChart=new Chart(ctx,{type:'line',data:{datasets:[{label:'Lämpötila',data:temps,borderColor:'#3b82f6',backgroundColor:'rgba(59,130,246,0.1)',tension:0.4,fill:true,pointRadius:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{type:'time',time:{unit:timeUnit,displayFormats:{minute:'HH:mm',hour:'HH:mm',day:'dd.MM'}},ticks:{color:'#94a3b8'}},y:{ticks:{color:'#94a3b8',stepSize:1,callback:v=>Math.round(v)+'°C'}}}}});"
"}catch(e){console.error('Chart error:',e);alert('Virhe ladattaessa dataa');}}"
"function changeTimeRange(hours){openChart(currentChartName,currentChartAddr,hours);}"
"function closeChart(){document.getElementById('chartModal').classList.remove('show');if(currentChart){currentChart.destroy();currentChart=null;}}"
"async function openSettings(tab='cloud'){"
"const modal=document.getElementById('settingsModal');modal.style.display='flex';"
"switchSettingsTab(tab);"
"if(tab==='cloud'){"
"try{const r=await fetch('/api/aio/config');const d=await r.json();"
"if(d.ok){document.getElementById('aioUser').value=d.username||'';"
"document.getElementById('aioEnabled').checked=d.enabled;"
"const types=d.feedTypes||3;"
"document.getElementById('feedTemp').checked=(types&1)!==0;"
"document.getElementById('feedHum').checked=(types&2)!==0;"
"document.getElementById('feedBat').checked=(types&4)!==0;"
"window.oldFeedTypes=types;}}"
"catch(e){console.error('Virhe ladattaessa AIO-asetuksia:',e);}}else if(tab==='scan'){"
"try{const r=await fetch('/api/scan-settings');const d=await r.json();"
"if(d.ok){document.getElementById('masterBleEnabled').checked=d.masterBleEnabled;}}"
"catch(e){console.error('Virhe ladattaessa skannausasetuksia:',e);}}}"
"function switchSettingsTab(tab){"
"document.querySelectorAll('.settings-tab-btn').forEach(b=>b.classList.remove('active'));"
"document.querySelectorAll('.settings-tab-content').forEach(c=>c.style.display='none');"
"document.querySelector('[data-tab=\"'+tab+'\"]').classList.add('active');"
"document.getElementById('tab-'+tab).style.display='block';}"
"function closeSettings(){document.getElementById('settingsModal').style.display='none';}"
"async function saveScanSettings(){"
"const enabled=document.getElementById('masterBleEnabled').checked;"
"try{const r=await fetch('/api/scan-settings',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({masterBleEnabled:enabled})});"
"const d=await r.json();if(d.ok){alert('Skannausasetukset tallennettu!');}else{alert('Virhe: '+d.error);}}"
"catch(e){alert('Virhe tallennettaessa: '+e.message);}}"
"async function saveAioSettings(){"
"const user=document.getElementById('aioUser').value;"
"const key=document.getElementById('aioKey').value;"
"const enabled=document.getElementById('aioEnabled').checked;"
"if(!user||!key){alert('Täytä käyttäjänimi ja avain!');return;}"
"const temp=document.getElementById('feedTemp').checked;"
"const hum=document.getElementById('feedHum').checked;"
"const bat=document.getElementById('feedBat').checked;"
"const feedTypes=(temp?1:0)|(hum?2:0)|(bat?4:0);"
"try{const r=await fetch('/api/aio/config',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({username:user,key:key,enabled:enabled,feedTypes:feedTypes})});"
"const d=await r.json();if(d.ok){alert('Pilvi-asetukset tallennettu!');window.oldFeedTypes=feedTypes;}else{alert('Virhe: '+d.error);}}"
"catch(e){alert('Virhe tallennettaessa: '+e.message);}}"
"async function sendAioNow(){"
"try{const r=await fetch('/api/aio/send_now',{method:'POST'});"
"const d=await r.json();if(d.ok){alert('Lähetys aloitettu! Tarkista Adafruit IO muutaman sekunnin kuluttua.');}else{alert('Virhe: '+(d.error||'Tuntematon'));}}"
"catch(e){alert('Virhe: '+e.message);}}"
"async function createAioFeeds(){"
"const temp=document.getElementById('feedTemp').checked;"
"const hum=document.getElementById('feedHum').checked;"
"const bat=document.getElementById('feedBat').checked;"
"if(!temp&&!hum&&!bat){alert('Valitse vähintään yksi datatyyppi ensin!');return;}"
"const feedTypes=(temp?1:0)|(hum?2:0)|(bat?4:0);"
"const oldTypes=window.oldFeedTypes||0;"
"const removed=oldTypes&(~feedTypes);"
"if(removed!==0){"
"const names=[];"
"if(removed&1)names.push('Lämpötila');"
"if(removed&2)names.push('Kosteus');"
"if(removed&4)names.push('Akku');"
"const msg='⚠️ VAROITUS!\\n\\nPoistat seuraavat datatyypit:\\n• '+names.join('\\n• ')+'\\n\\nTämä POISTAA kaikki vastaavat feedit ja KAIKEN niiden datan PYSYVÄSTI!\\n\\nHaluatko varmasti jatkaa?';"
"if(!confirm(msg))return;"
"try{"
"const dr=await fetch('/api/aio/delete_feeds?types='+removed,{method:'DELETE'});"
"const dd=await dr.json();"
"if(!dd.ok){alert('Feedien poisto epäonnistui: '+dd.error);return;}"
"alert('Poistettiin '+dd.deleted+' feediä');"
"}catch(e){alert('Virhe poistettaessa: '+e.message);return;}}"
"try{"
"const user=document.getElementById('aioUser').value;"
"const key=document.getElementById('aioKey').value;"
"if(!user||!key){alert('Syötä ensin käyttäjänimi ja AIO Key Pilvi-asetuksiin!');return;}"
"const r2=await fetch('/api/aio/config',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({username:user,key:key,enabled:true,feedTypes:feedTypes})});"
"const d2=await r2.json();"
"if(!d2.ok){alert('Asetusten tallennus epäonnistui');return;}"
"window.oldFeedTypes=feedTypes;"
"}catch(e){alert('Virhe: '+e.message);return;}"
"if(!confirm('Luodaanko feedit automaattisesti kaikille näkyville laitteille?'))return;"
"const btn=event.target;btn.disabled=true;btn.textContent='⏳ Luodaan...';"
"try{const r=await fetch('/api/aio/create_feeds',{method:'POST'});"
"const d=await r.json();if(d.ok){alert('✅ Luotiin '+d.count+' feediä!\\n\\nNyt voit testata lähetystä.');}else{alert('Virhe: '+(d.error||'Tuntematon'));}"
"btn.disabled=false;btn.textContent='🔧 Luo feedit automaattisesti';}"
"catch(e){alert('Virhe: '+e.message);btn.disabled=false;btn.textContent='🔧 Luo feedit automaattisesti';}}"
"function updateFeedCount(){"
"const temp=document.getElementById('feedTemp').checked;"
"const hum=document.getElementById('feedHum').checked;"
"const bat=document.getElementById('feedBat').checked;"
"const types=(temp?1:0)+(hum?1:0)+(bat?1:0);"
"const label=document.getElementById('feedCountLabel');"
"if(types>0){label.textContent='Arvio: '+(5*types)+' feediä 5 laitteella';"
"label.style.color=types<=2?'#10b981':'#f59e0b';}else{label.textContent='Valitse datatyypit';"
"label.style.color='#94a3b8';}}"
"function openAioHelp(){"
"document.getElementById('aioHelpModal').classList.add('show');}"
"function closeAioHelp(){"
"document.getElementById('aioHelpModal').classList.remove('show');}"
"setInterval(updateDevices,2000);updateDevices();"
"</script>"
"<div id='settingsModal' class='modal'><div class='modal-content' style='max-width:700px;'>"
"<div class='modal-header'><h2>⚙️ Asetukset</h2>"
"<button class='modal-close' onclick='closeSettings()'>×</button></div>"
"<div class='settings-tabs'>"
"<button class='settings-tab-btn active' data-tab='cloud' onclick='switchSettingsTab(\"cloud\")'>☁️ Pilvi</button>"
"<button class='settings-tab-btn' data-tab='scan' onclick='switchSettingsTab(\"scan\")'>📡 Skannaus</button>"
"</div>"
"<div id='tab-cloud' class='settings-tab-content' style='display:block;'>"
"<div style='background:#0f172a;border:1px solid #334155;border-radius:12px;padding:16px;margin-bottom:20px;font-size:14px;color:#cbd5e1;line-height:1.6;'>"
"<strong style='color:#f1f5f9;'>Pika-ohje:</strong> Luo tili osoitteessa <a href='https://io.adafruit.com' target='_blank' style='color:#60a5fa;'>io.adafruit.com</a>, kopioi Username ja AIO Key (🔑), liitä alle, valitse datatyypit, tallenna ja luo feedit."
"</div>"
"<div style='margin-bottom:15px;'><label style='display:block;margin-bottom:5px;font-weight:600;'>Käyttäjänimi:</label>"
"<input type='text' id='aioUser' placeholder='esim. juhku' style='width:100%;padding:10px;border:1px solid #334155;border-radius:8px;background:#1e293b;color:#e2e8f0;'></div>"
"<div style='margin-bottom:15px;'><label style='display:block;margin-bottom:5px;font-weight:600;'>AIO Key:</label>"
"<input type='password' id='aioKey' placeholder='aio_...' style='width:100%;padding:10px;border:1px solid #334155;border-radius:8px;background:#1e293b;color:#e2e8f0;'></div>"
"<div style='margin-bottom:20px;'><label style='display:flex;align-items:center;gap:10px;'>"
"<input type='checkbox' id='aioEnabled' style='width:20px;height:20px;'><span>Lähetys käytössä (5 min välein)</span></label></div>"
"<div style='background:#1e293b;border:1px solid #334155;border-radius:12px;padding:16px;margin-bottom:20px;'>"
"<h3 style='margin-bottom:12px;font-size:16px;color:#f1f5f9;'>Valitse lähetettävät tiedot:</h3>"
"<div style='display:flex;flex-direction:column;gap:10px;'>"
"<label style='display:flex;align-items:center;gap:10px;cursor:pointer;'>"
"<input type='checkbox' id='feedTemp' style='width:18px;height:18px;' onchange='updateFeedCount()'><span>🌡️ Lämpötila</span></label>"
"<label style='display:flex;align-items:center;gap:10px;cursor:pointer;'>"
"<input type='checkbox' id='feedHum' style='width:18px;height:18px;' onchange='updateFeedCount()'><span>💧 Kosteus</span></label>"
"<label style='display:flex;align-items:center;gap:10px;cursor:pointer;'>"
"<input type='checkbox' id='feedBat' style='width:18px;height:18px;' onchange='updateFeedCount()'><span>🔋 Akku</span></label>"
"</div>"
"<div id='feedCountEstimate' style='margin-top:12px;padding:10px;background:#0f172a;border-radius:8px;font-size:13px;color:#94a3b8;'></div>"
"</div>"
"<button onclick='saveAioSettings()' style='width:100%;padding:12px;background:#10b981;color:white;border:none;border-radius:8px;font-weight:600;cursor:pointer;margin-bottom:10px;'>💾 Tallenna</button>"
"<button onclick='createAioFeeds()' style='width:100%;padding:12px;background:#f59e0b;color:white;border:none;border-radius:8px;font-weight:600;cursor:pointer;margin-bottom:10px;'>🔧 Luo feedit automaattisesti</button>"
"<button onclick='sendAioNow()' style='width:100%;padding:12px;background:#3b82f6;color:white;border:none;border-radius:8px;font-weight:600;cursor:pointer;'>📤 Testaa lähetys</button>"
"<button onclick='openAioHelp()' style='width:100%;padding:10px;background:transparent;color:#94a3b8;border:1px solid #334155;border-radius:8px;font-weight:500;cursor:pointer;margin-top:10px;'>📖 Näytä yksityiskohtaiset ohjeet</button>"
"</div>"
"<div id='tab-scan' class='settings-tab-content'>"
"<div style='background:#0f172a;border:1px solid #334155;border-radius:12px;padding:16px;margin-bottom:20px;font-size:14px;color:#cbd5e1;line-height:1.6;'>"
"<strong style='color:#f1f5f9;'>Skannausasetukset</strong> - Määritä miten BLE-laitteiden haku toimii."
"</div>"
"<div style='margin-bottom:20px;'>"
"<h3 style='margin-bottom:12px;font-size:16px;color:#f1f5f9;'>Paikallinen BLE-skannaus</h3>"
"<label style='display:flex;align-items:center;gap:10px;margin-bottom:10px;'>"
"<input type='checkbox' id='masterBleEnabled' checked style='width:20px;height:20px;'>"
"<span>Käytä laitteen omaa BLE-antenniå</span>"
"</label>"
"<div style='padding:12px;background:#0f172a;border-left:3px solid #f59e0b;border-radius:4px;font-size:13px;color:#94a3b8;'>"
"⚠️ Jos poistat tämän käytöstä, laite luottaa vain satelliittien dataan."
"</div>"
"</div>"
"<button onclick='saveScanSettings()' style='width:100%;padding:12px;background:#10b981;color:white;border:none;border-radius:8px;font-weight:600;cursor:pointer;'>💾 Tallenna</button>"
"</div>"
"</div></div>"
"<div id='aioHelpModal' class='modal'><div class='modal-content' style='max-width:700px;'>"
"<div class='modal-header'><h2>📖 Adafruit IO Käyttöönotto</h2>"
"<button class='modal-close' onclick='closeAioHelp()'>×</button></div>"
"<div style='padding:24px;'>"
"<div style='background:#0f172a;border:1px solid #334155;border-radius:12px;padding:20px;margin-bottom:20px;'>"
"<h3 style='margin-bottom:15px;color:#f1f5f9;font-size:18px;'>Vaiheittainen ohje</h3>"
"<ol style='margin-left:20px;line-height:2.2;color:#cbd5e1;font-size:15px;'>"
"<li>Luo <strong>ilmainen tili</strong> osoitteessa <a href='https://io.adafruit.com' target='_blank' style='color:#60a5fa;text-decoration:underline;'>io.adafruit.com</a></li>"
"<li>Kirjaudu sisään ja klikkaa <strong>keltaista avain-ikonia (🔑)</strong> oikeassa yläkulmassa</li>"
"<li>Kopioi <strong>Username</strong> ja <strong>AIO Key</strong></li>"
"<li>Palaa ☁️ Pilvi-popuppiin ja liitä tiedot kenttiin</li>"
"<li>Valitse <strong>lähetettävät datatyypit</strong> (lämpötila/kosteus/akku)</li>"
"<li>Klikkaa <strong>\"💾 Tallenna ja sulje\"</strong></li>"
"<li>Avaa ☁️ Pilvi uudelleen ja klikkaa <strong>\"🔧 Luo feedit automaattisesti\"</strong></li>"
"<li>Testaa lähetystä <strong>\"📤 Testaa lähetys\"</strong> -painikkeella</li>"
"<li>Tarkista <a href='https://io.adafruit.com' target='_blank' style='color:#60a5fa;text-decoration:underline;'>io.adafruit.com</a> että data näkyy feedeissä</li>"
"<li>✅ Valmis! Data lähetetään automaattisesti 5 minuutin välein</li>"
"</ol>"
"</div>"
"<div style='background:#1e3a4c;border-left:4px solid #3b82f6;padding:15px;border-radius:8px;margin-bottom:20px;'>"
"<p style='margin:0;font-size:14px;color:#bfdbfe;'><strong>💡 Ilmaisversion rajoitukset:</strong></p>"
"<ul style='margin:10px 0 0 20px;color:#93c5fd;line-height:1.8;'>"
"<li>Maksimi <strong>10 feediä</strong> per käyttäjä</li>"
"<li>Maksimi <strong>30 viestiä minuutissa</strong></li>"
"<li>Valitse datatyypit tarpeen mukaan (temp/hum/bat)</li>"
"</ul>"
"</div>"
"<button onclick='closeAioHelp()' style='width:100%;padding:12px;background:#6366f1;color:white;border:none;border-radius:8px;font-weight:600;cursor:pointer;'>✓ Selvä</button>"
"</div></div></div>"
"<div id='chartModal' class='modal'><div class='modal-content' style='max-width:900px;'>"
"<div class='modal-header'><h2 id='chartTitle'>📊 Lämpötilahistoria</h2>"
"<button class='modal-close' onclick='closeChart()'>×</button></div>"
"<div style='padding:24px;'>"
"<div style='display:flex;gap:8px;margin-bottom:16px;'>"
"<button onclick='changeTimeRange(1)' class='time-btn' data-hours='1'>1h</button>"
"<button onclick='changeTimeRange(24)' class='time-btn active' data-hours='24'>24h</button>"
"<button onclick='changeTimeRange(168)' class='time-btn' data-hours='168'>Viikko</button>"
"<button onclick='changeTimeRange(720)' class='time-btn' data-hours='720'>Kuukausi</button>"
"</div>"
"<div style='height:400px;'><canvas id='chartCanvas'></canvas></div>"
"</div></div></div>"
"</body>"
"</html>";

#endif // WEBSERVER_H
