#ifndef WEBSERVER_H
#define WEBSERVER_H

// HTML-sivu BLE-skannerin web-käyttöliittymälle
const char HTML_PAGE[] = 
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1.0'>"
"<title>BLE Laitteet</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
"background:#0f172a;min-height:100vh;padding:20px;color:#e2e8f0}"
".container{max-width:1000px;margin:0 auto}"
".header{display:flex;justify-content:space-between;align-items:center;margin-bottom:32px;"
"padding:24px;background:linear-gradient(135deg,#1e293b 0%,#334155 100%);"
"border-radius:16px;box-shadow:0 4px 24px rgba(0,0,0,0.4)}"
"h1{color:#f1f5f9;font-size:28px;margin:0;font-weight:700;letter-spacing:-0.5px;"
"display:flex;align-items:center;gap:12px}"
"h1::before{content:'📡';font-size:32px}"
".toggle-btn{background:#334155;color:#e2e8f0;border:1px solid #475569;"
"padding:10px 20px;border-radius:8px;cursor:pointer;font-size:14px;font-weight:600;"
"transition:all 0.2s;box-shadow:0 2px 8px rgba(0,0,0,0.2)}"
".toggle-btn:hover{background:#475569;border-color:#64748b;transform:translateY(-1px);"
"box-shadow:0 4px 12px rgba(0,0,0,0.3)}"
".toggle-btn.active{background:#3b82f6;border-color:#3b82f6;color:white}"
".device-card{background:#1e293b;border:1px solid #334155;border-radius:12px;padding:24px;"
"margin-bottom:16px;box-shadow:0 2px 16px rgba(0,0,0,0.3);position:relative;transition:all 0.2s;z-index:1}"
".device-card.settings-open{z-index:100}"
".device-card:hover{border-color:#475569;box-shadow:0 4px 24px rgba(0,0,0,0.4);transform:translateY(-2px)}"
".device-card.unsaved{border:2px dashed #10b981;background:#0a3428}"
".device-card.unsaved .device-name::after{content:' (ei tallennettu)';font-size:12px;color:#10b981;font-weight:400}"
".device-header{display:flex;justify-content:space-between;align-items:flex-start}"
".device-info{flex:1}"
".device-name{font-size:18px;font-weight:700;color:#f1f5f9;margin-bottom:6px;letter-spacing:-0.3px}"
".device-mac{font-family:'JetBrains Mono','Courier New',monospace;font-size:12px;color:#64748b;"
"background:#0f172a;padding:4px 8px;border-radius:4px;display:inline-block;margin-top:4px}"
".settings-icon{background:none;border:none;font-size:24px;cursor:pointer;padding:8px;"
"color:#64748b;transition:all 0.2s;border-radius:8px}"
".settings-icon:hover{color:#e2e8f0;background:#334155;transform:rotate(90deg)}"
".settings-panel{display:none;position:absolute;right:16px;top:60px;background:#1e293b;"
"border:1px solid #334155;border-radius:12px;box-shadow:0 8px 32px rgba(0,0,0,0.5);"
"min-width:240px;z-index:9999}"
".settings-panel.open{display:block}"
".settings-option{padding:12px 16px;cursor:pointer;transition:background 0.2s;"
"border-bottom:1px solid #334155;color:#e2e8f0}"
".settings-option:last-child{border-bottom:none}"
".settings-option:hover{background:#334155}"
".settings-option.danger{color:#f87171}"
".settings-option.danger:hover{background:#450a0a;color:#fca5a5}"
".sensor-data{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));"
"gap:16px;margin-top:20px;padding-top:20px;border-top:1px solid #334155}"
".sensor-value{text-align:center;background:#0f172a;padding:16px;border-radius:8px;"
"border:1px solid #1e293b;transition:all 0.2s}"
".sensor-value:hover{border-color:#334155;transform:translateY(-2px)}"
".sensor-value.primary{grid-column:span 1;background:linear-gradient(135deg,#1e293b,#334155);"
"border:2px solid #3b82f6;padding:20px}"
".sensor-label{font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:0.8px;"
"margin-bottom:8px;font-weight:600}"
".sensor-value.primary .sensor-label{font-size:12px;color:#60a5fa;font-weight:700}"
".sensor-number{font-size:26px;font-weight:700;color:#3b82f6}"
".sensor-value.primary .sensor-number{font-size:42px;color:#60a5fa;text-shadow:0 0 20px rgba(96,165,250,0.3)}"
".sensor-unit{font-size:13px;color:#64748b;margin-left:2px;font-weight:500}"
".sensor-value.primary .sensor-unit{font-size:18px;color:#93c5fd}"
".temp-cold{color:#60a5fa !important}"
".temp-cool{color:#34d399 !important}"
".temp-normal{color:#fbbf24 !important}"
".temp-warm{color:#fb923c !important}"
".temp-hot{color:#f87171 !important}"
".battery-container{display:flex;flex-direction:column;align-items:center;gap:8px}"
".battery-bar{width:80px;height:22px;border:2px solid #475569;border-radius:6px;position:relative;"
"background:#0f172a;overflow:hidden}"
".battery-bar::after{content:'';position:absolute;top:50%;right:-7px;transform:translateY(-50%);"
"width:4px;height:12px;background:#475569;border-radius:0 3px 3px 0}"
".battery-fill{height:100%;border-radius:3px;transition:width 0.3s,background 0.3s}"
".battery-fill.high{background:linear-gradient(90deg,#10b981,#34d399)}"
".battery-fill.medium{background:linear-gradient(90deg,#f59e0b,#fbbf24)}"
".battery-fill.low{background:linear-gradient(90deg,#ef4444,#f87171)}"
".signal-container{display:flex;align-items:center;gap:8px;justify-content:center}"
".signal-bars{display:flex;align-items:flex-end;gap:3px;height:20px}"
".signal-bar{width:5px;border-radius:2px;transition:background 0.3s}"
".signal-bar:nth-child(1){height:25%}"
".signal-bar:nth-child(2){height:50%}"
".signal-bar:nth-child(3){height:75%}"
".signal-bar:nth-child(4){height:100%}"
".signal-bar.active.excellent,.signal-bar.active.good{background:#10b981}"
".signal-bar.active.fair{background:#f59e0b}"
".signal-bar.active.poor{background:#ef4444}"
".signal-bar.inactive{background:#334155}"
".rssi{display:inline-block;margin-top:12px;padding:6px 12px;background:#0f172a;"
"border-radius:6px;font-size:12px;color:#94a3b8;border:1px solid #1e293b}"
".no-devices{text-align:center;padding:60px 20px;color:#64748b;font-size:18px;font-weight:500}"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<div class='header'>"
"<h1>BLE-laitteet</h1>"
"<div style='display:flex;gap:12px;'>"
"<button class='toggle-btn' id='scanBtn' onclick='startScan()'>🔍 Skannaa uusia</button>"
"</div>"
"</div>"
"<div id='devices'></div>"
"</div>"
"<script>"
"let openSettings=null;"
"let scanCountdown=0;"
"let scanInterval=null;"
"async function startScan(){"
"const btn=document.getElementById('scanBtn');"
"btn.disabled=true;"
"btn.textContent='⏳ Käynnistetään...';"
"try{"
"const resp=await fetch('/api/start-scan',{method:'POST'});"
"const result=await resp.json();"
"if(result.ok){"
"scanCountdown=result.duration;"
"btn.textContent='⏳ Skannaa ('+scanCountdown+'s)';"
"scanInterval=setInterval(()=>{"
"scanCountdown--;"
"if(scanCountdown<=0){"
"clearInterval(scanInterval);"
"btn.textContent='🔍 Skannaa uusia';"
"btn.disabled=false;"
"}else{"
"btn.textContent='⏳ Skannaa ('+scanCountdown+'s)';}"
"},1000);"
"}else{"
"alert('Skannauksen käynnistys epäonnistui: '+result.error);"
"btn.textContent='🔍 Skannaa uusia';"
"btn.disabled=false;}"
"}catch(err){"
"console.error('Virhe:',err);"
"alert('Virhe skannauksen käynnistyksessä!');"
"btn.textContent='🔍 Skannaa uusia';"
"btn.disabled=false;}}"
"function toggleSettings(addr){"
"const panel=document.getElementById('settings-'+addr);"
"const card=panel?panel.closest('.device-card'):null;"
"if(openSettings&&openSettings!==panel){"
"openSettings.classList.remove('open');"
"const oldCard=openSettings.closest('.device-card');"
"if(oldCard)oldCard.classList.remove('settings-open');}"
"if(panel){"
"panel.classList.toggle('open');"
"const isOpen=panel.classList.contains('open');"
"openSettings=isOpen?panel:null;"
"if(card)card.classList.toggle('settings-open',isOpen);}}"
"document.addEventListener('click',(e)=>{"
"if(!e.target.closest('.settings-icon')&&!e.target.closest('.settings-panel')){"
"if(openSettings){"
"openSettings.classList.remove('open');"
"const card=openSettings.closest('.device-card');"
"if(card)card.classList.remove('settings-open');"
"openSettings=null;}}});"
"async function hideDevice(addr,event){"
"if(event){event.stopPropagation();}"
"console.log('Poistetaan laite NVS:stä:',addr);"
"if(openSettings){openSettings.classList.remove('open');openSettings=null;}"
"try{"
"const resp=await fetch('/api/toggle-visibility',{method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:'addr='+encodeURIComponent(addr)+'&visible=0'});"
"const result=await resp.json();"
"console.log('Vastaus:',result);"
"setTimeout(updateDevices,100);"
"}catch(err){console.error('Virhe:',err);}}"
"async function showDevice(addr,event){"
"if(event){event.stopPropagation();}"
"console.log('Tallennetaan laite NVS:ään:',addr);"
"if(openSettings){openSettings.classList.remove('open');openSettings=null;}"
"try{"
"const resp=await fetch('/api/toggle-visibility',{method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:'addr='+encodeURIComponent(addr)+'&visible=1'});"
"const result=await resp.json();"
"console.log('Vastaus:',result);"
"setTimeout(updateDevices,100);"
"}catch(err){console.error('Virhe:',err);}}"
"async function saveSettings(addr,addrClean,applyToSimilar,event){"
"if(event){event.stopPropagation();}"
"const name=document.getElementById('name-'+addrClean).value;"
"const showMac=document.getElementById('showmac-'+addrClean).checked?1:0;"
"let fieldMask=0;"
"document.querySelectorAll('#settings-'+addrClean+' .field-check').forEach(cb=>{"
"if(cb.checked){fieldMask|=parseInt(cb.getAttribute('data-bit'));}});"
"console.log('Tallennetaan:',addr,'name=',name,'showMac=',showMac,'fields=',fieldMask,'apply=',applyToSimilar);"
"try{"
"const resp=await fetch('/api/update-settings',{method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:'addr='+encodeURIComponent(addr)+'&name='+encodeURIComponent(name)+'&show_mac='+showMac+'&field_mask='+fieldMask+'&apply_to_similar='+(applyToSimilar?1:0)});"
"const result=await resp.json();"
"console.log('Vastaus:',result);"
"if(result.updated>1){"
"alert('Asetukset tallennettu '+result.updated+' laitteelle!');"
"}else{"
"alert('Asetukset tallennettu!');}"
"if(openSettings){openSettings.classList.remove('open');openSettings=null;}"
"setTimeout(updateDevices,100);"
"}catch(err){console.error('Virhe:',err);alert('Virhe tallennettaessa!');}}"
"async function updateDevices(){"
"if(openSettings){console.log('Asetukset auki, ohitetaan päivitys');return;}"
"try{"
"const url='/api/devices';"
"const res=await fetch(url);"
"const data=await res.json();"
"console.log('Löydetty',data.length,'laitetta');"
"if(data.length===0){document.getElementById('devices').innerHTML="
"'<div class=\"no-devices\">Ei näytettäviä laitteita</div>';return;}"
"let html='';"
"data.forEach(d=>{"
"const name=d.name||'Nimetön laite';"
"const addrClean=d.addr.replace(/:/g,'');"
"const savedClass=d.saved?'':'unsaved';"
"html+='<div class=\"device-card '+savedClass+'\">'"
"+' <div class=\"device-header\">'"
"+' <div class=\"device-info\">'"
"+' <div class=\"device-name\">'+name+'</div>';"
"if(d.showMac){"
"html+=' <div class=\"device-mac\">'+d.addr+'</div>';}"
"html+=' </div>'"
"+' <button class=\"settings-icon\" onclick=\"toggleSettings(\\''+addrClean+'\\')\" >⚙️</button>'"
"+' <div class=\"settings-panel\" id=\"settings-'+addrClean+'\">';"
"html+=' <div style=\"padding:14px;\">'"
"+' <label style=\"display:block;margin-bottom:6px;font-weight:600;color:#f1f5f9;font-size:13px;\">Nimi:</label>'"
"+' <input type=\"text\" id=\"name-'+addrClean+'\" value=\"'+name+'\" style=\"width:100%;padding:8px;margin-bottom:12px;border:1px solid #475569;border-radius:6px;background:#0f172a;color:#e2e8f0;font-size:14px;\" />'"
"+' <label style=\"display:flex;align-items:center;margin-bottom:12px;color:#e2e8f0;cursor:pointer;\">'"
"+' <input type=\"checkbox\" id=\"showmac-'+addrClean+'\" '+(d.showMac?'checked':'')+' style=\"margin-right:8px;cursor:pointer;\" />'"
"+' <span style=\"font-size:13px;\">Näytä MAC-osoite</span>'"
"+' </label>'"
"+' <div style=\"margin-bottom:10px;font-weight:600;color:#f1f5f9;font-size:13px;\">Näytettävät kentät:</div>';"
"const fields=[{bit:1,label:'Lämpötila'},{bit:2,label:'Kosteus'},{bit:4,label:'Akku %'},{bit:8,label:'Jännite'},{bit:16,label:'Signaali'}];"
"fields.forEach(f=>{"
"const available=(d.availableFields&f.bit)!==0;"
"const checked=(d.fieldMask&f.bit)!==0;"
"if(available){"
"html+=' <label style=\"display:flex;align-items:center;margin-bottom:6px;color:#e2e8f0;cursor:pointer;\">'"
"+' <input type=\"checkbox\" class=\"field-check\" data-bit=\"'+f.bit+'\" '+(checked?'checked':'')+' style=\"margin-right:8px;cursor:pointer;\" />'"
"+' <span style=\"font-size:13px;\">'+f.label+'</span> </label>';}});"
"html+=' <button onclick=\"saveSettings(\\''+d.addr+'\\',\\''+addrClean+'\\',false,event)\" style=\"width:100%;padding:10px;margin-top:14px;background:#3b82f6;color:white;border:none;border-radius:6px;cursor:pointer;font-weight:600;font-size:13px;transition:background 0.2s;\" onmouseover=\"this.style.background=\\'#2563eb\\'\" onmouseout=\"this.style.background=\\'#3b82f6\\'\">💾 Tallenna</button>'"
"+' <button onclick=\"saveSettings(\\''+d.addr+'\\',\\''+addrClean+'\\',true,event)\" style=\"width:100%;padding:10px;margin-top:6px;background:#10b981;color:white;border:none;border-radius:6px;cursor:pointer;font-weight:600;font-size:13px;transition:background 0.2s;\" onmouseover=\"this.style.background=\\'#059669\\'\" onmouseout=\"this.style.background=\\'#10b981\\'\">🔁 Sovella samanlaisiin</button>';"
"if(d.saved){"
"html+=' <div class=\"settings-option danger\" onclick=\"hideDevice(\\''+d.addr+'\\',event)\" style=\"margin-top:10px;\">🗑️ Poista</div>';"
"}else{"
"html+=' <div class=\"settings-option\" onclick=\"showDevice(\\''+d.addr+'\\',event)\" style=\"margin-top:10px;background:#10b981;\">💾 Tallenna</div>';}"
"html+=' </div></div>'"
"+' </div>';"
"if(d.hasSensor){"
"html+=' <div class=\"sensor-data\">';"
"if((d.fieldMask&1)&&d.temp){"
"let tempClass='temp-normal';"
"if(d.temp<10)tempClass='temp-cold';"
"else if(d.temp<18)tempClass='temp-cool';"
"else if(d.temp>26)tempClass='temp-warm';"
"else if(d.temp>30)tempClass='temp-hot';"
"html+=' <div class=\"sensor-value primary\">'"
"+' <div class=\"sensor-label\">🌡️ Lämpötila</div>'"
"+' <div class=\"sensor-number '+tempClass+'\">'+d.temp.toFixed(1)+'<span class=\"sensor-unit\">°C</span></div>'"
"+' </div>';}"
"if((d.fieldMask&2)&&d.hum){"
"html+=' <div class=\"sensor-value\">'"
"+' <div class=\"sensor-label\">💧 Kosteus</div>'"
"+' <div class=\"sensor-number\">'+d.hum+'<span class=\"sensor-unit\">%</span></div>'"
"+' </div>';}"
"if((d.fieldMask&4)&&d.bat){"
"const batClass=d.bat>50?'high':(d.bat>20?'medium':'low');"
"html+=' <div class=\"sensor-value\">'"
"+' <div class=\"sensor-label\">🔋 Akku</div>'"
"+' <div class=\"battery-container\">'"
"+' <div class=\"battery-bar\"><div class=\"battery-fill '+batClass+'\" style=\"width:'+d.bat+'%\"></div></div>'"
"+' <div class=\"sensor-number\" style=\"font-size:18px;\">'+d.bat+'%</div>'"
"+' </div>'"
"+' </div>';}"
"if((d.fieldMask&8)&&d.batMv){"
"html+=' <div class=\"sensor-value\">'"
"+' <div class=\"sensor-label\">⚡ Jännite</div>'"
"+' <div class=\"sensor-number\">'+d.batMv+'<span class=\"sensor-unit\">mV</span></div>'"
"+' </div>';}"
"html+=' </div>';}"
"if(d.fieldMask&16){"
"let barCount=0,signalClass='';"
"if(d.rssi>=-50){barCount=4;signalClass='excellent';}"
"else if(d.rssi>=-65){barCount=3;signalClass='good';}"
"else if(d.rssi>=-75){barCount=2;signalClass='fair';}"
"else{barCount=1;signalClass='poor';}"
"html+=' <div class=\"rssi\"><div class=\"signal-container\">'"
"+' <div class=\"signal-bars\">';"
"for(let i=1;i<=4;i++){"
"html+='<div class=\"signal-bar '+(i<=barCount?'active '+signalClass:'inactive')+'\"></div>';}"
"html+=' </div><span style=\"font-size:13px;color:#7f8c8d;\">'+d.rssi+' dBm</span></div></div>';}"
"html+='</div>';});"
"document.getElementById('devices').innerHTML=html;"
"}catch(error){console.error('Virhe haettaessa laitteita:',error);}}"
"setInterval(updateDevices,2000);updateDevices();"
"</script>"
"</body>"
"</html>";

#endif // WEBSERVER_H
