#ifndef WEBSERVER_H
#define WEBSERVER_H

// HTML-sivu BLE-skannerin web-käyttöliittymälle
const char HTML_PAGE[] = 
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1.0'>"
"<title>BLE Laitteet</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
"background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);min-height:100vh;padding:20px}"
".container{max-width:900px;margin:0 auto}"
".header{display:flex;justify-content:space-between;align-items:center;margin-bottom:30px}"
"h1{color:white;font-size:32px;margin:0;text-shadow:2px 2px 4px rgba(0,0,0,0.3)}"
".toggle-btn{background:rgba(255,255,255,0.2);color:white;border:2px solid rgba(255,255,255,0.4);"
"padding:10px 20px;border-radius:8px;cursor:pointer;font-size:14px;font-weight:600;"
"transition:all 0.3s;backdrop-filter:blur(10px)}"
".toggle-btn:hover{background:rgba(255,255,255,0.3);border-color:rgba(255,255,255,0.6);"
"transform:translateY(-2px)}"
".toggle-btn.active{background:white;color:#667eea;border-color:white}"
".device-card{background:white;border-radius:16px;padding:24px;margin-bottom:16px;"
"box-shadow:0 4px 12px rgba(0,0,0,0.15);position:relative;transition:transform 0.2s}"
".device-card:hover{transform:translateY(-3px);box-shadow:0 8px 20px rgba(0,0,0,0.2)}"
".device-card.hidden{opacity:0.6;background:#f5f5f5;border:2px dashed #bbb}"
".device-card.hidden .device-name{color:#999}"
".device-header{display:flex;justify-content:space-between;align-items:flex-start}"
".device-info{flex:1}"
".device-name{font-size:20px;font-weight:600;color:#2c3e50;margin-bottom:4px}"
".device-mac{font-family:'Courier New',monospace;font-size:13px;color:#7f8c8d}"
".settings-icon{background:none;border:none;font-size:28px;cursor:pointer;padding:8px;"
"opacity:0.5;transition:all 0.2s;border-radius:8px}"
".settings-icon:hover{opacity:1;background:#f8f9fa;transform:rotate(90deg)}"
".settings-panel{display:none;position:absolute;right:16px;top:60px;background:white;"
"border:1px solid #e0e0e0;border-radius:12px;box-shadow:0 6px 20px rgba(0,0,0,0.15);"
"min-width:220px;z-index:1000}"
".settings-panel.open{display:block}"
".settings-option{padding:14px 20px;cursor:pointer;transition:background 0.2s;"
"border-bottom:1px solid #f0f0f0}"
".settings-option:last-child{border-bottom:none}"
".settings-option:hover{background:#f8f9fa}"
".settings-option.danger{color:#e74c3c}"
".settings-option.danger:hover{background:#ffebee}"
".sensor-data{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));"
"gap:16px;margin-top:20px;padding-top:20px;border-top:2px solid #f0f0f0}"
".sensor-value{text-align:center}"
".sensor-label{font-size:12px;color:#95a5a6;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px}"
".sensor-number{font-size:28px;font-weight:700;color:#667eea}"
".sensor-unit{font-size:14px;color:#7f8c8d;margin-left:2px}"
".rssi{display:inline-block;margin-top:12px;padding:6px 12px;background:#ecf0f1;"
"border-radius:6px;font-size:13px;color:#7f8c8d}"
".no-devices{text-align:center;padding:60px 20px;color:rgba(255,255,255,0.9);font-size:20px}"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<div class='header'>"
"<h1>📡 BLE-laitteet</h1>"
"<button class='toggle-btn' id='toggleBtn' onclick='toggleHidden()'>👁️ Näytä piilotetut</button>"
"</div>"
"<div id='devices'></div>"
"</div>"
"<script>"
"let openSettings=null;"
"let showHidden=false;"
"function toggleHidden(){"
"showHidden=!showHidden;"
"const btn=document.getElementById('toggleBtn');"
"btn.textContent=showHidden?'👁️ Piilota piilotetut':'👁️ Näytä piilotetut';"
"btn.classList.toggle('active',showHidden);"
"updateDevices();}"
"function toggleSettings(addr){"
"const panel=document.getElementById('settings-'+addr);"
"if(openSettings&&openSettings!==panel){openSettings.classList.remove('open');}"
"if(panel){panel.classList.toggle('open');openSettings=panel.classList.contains('open')?panel:null;}}"
"document.addEventListener('click',(e)=>{"
"if(!e.target.closest('.settings-icon')&&!e.target.closest('.settings-panel')){"
"if(openSettings){openSettings.classList.remove('open');openSettings=null;}}});"
"async function hideDevice(addr,event){"
"if(event){event.stopPropagation();}"
"console.log('Piilotetaan laite:',addr);"
"if(openSettings){openSettings.classList.remove('open');openSettings=null;}"
"try{"
"const resp=await fetch('/api/toggle-visibility',{method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:'addr='+encodeURIComponent(addr)+'&visible=0'});"
"const result=await resp.json();"
"console.log('Vastaus:',result);"
"setTimeout(updateDevices,100);"
"}catch(err){console.error('Virhe:',err);}}"
"async function showDevice(addr,event){"
"if(event){event.stopPropagation();}"
"console.log('Näytetään laite:',addr);"
"if(openSettings){openSettings.classList.remove('open');openSettings=null;}"
"try{"
"const resp=await fetch('/api/toggle-visibility',{method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:'addr='+encodeURIComponent(addr)+'&visible=1'});"
"const result=await resp.json();"
"console.log('Vastaus:',result);"
"setTimeout(updateDevices,100);"
"}catch(err){console.error('Virhe:',err);}}"
"async function updateDevices(){"
"try{"
"const url='/api/devices'+(showHidden?'?all=1':'');"
"console.log('Haetaan:',url,'showHidden=',showHidden);"
"const openPanelId=openSettings?openSettings.id:null;"
"const res=await fetch(url);"
"const data=await res.json();"
"console.log('Löydetty',data.length,'laitetta');"
"if(data.length===0){document.getElementById('devices').innerHTML="
"'<div class=\"no-devices\">Ei näytettäviä laitteita</div>';return;}"
"let html='';"
"data.forEach(d=>{"
"const name=d.name||'Nimetön laite';"
"const addrClean=d.addr.replace(/:/g,'');"
"const hiddenClass=d.visible?'':'hidden';"
"console.log('Laite:',d.addr,'visible=',d.visible,'class=',hiddenClass);"
"html+='<div class=\"device-card '+hiddenClass+'\">'"
"+' <div class=\"device-header\">'"
"+' <div class=\"device-info\">'"
"+' <div class=\"device-name\">'+name+'</div>'"
"+' <div class=\"device-mac\">'+d.addr+'</div>'"
"+' </div>'"
"+' <button class=\"settings-icon\" onclick=\"toggleSettings(\\''+addrClean+'\\')\" >⚙️</button>'"
"+' <div class=\"settings-panel\" id=\"settings-'+addrClean+'\">';"
"if(d.visible){"
"html+=' <div class=\"settings-option danger\" onclick=\"hideDevice(\\''+d.addr+'\\',event)\" >🚫 Piilota laite</div>';"
"}else{"
"html+=' <div class=\"settings-option\" onclick=\"showDevice(\\''+d.addr+'\\',event)\" >✅ Näytä laite</div>';}"
"html+=' </div>'"
"+' </div>';"
"if(d.hasSensor){"
"html+=' <div class=\"sensor-data\">'"
"+' <div class=\"sensor-value\">'"
"+' <div class=\"sensor-label\">Lämpötila</div>'"
"+' <div class=\"sensor-number\">'+d.temp.toFixed(1)+'<span class=\"sensor-unit\">°C</span></div>'"
"+' </div>'"
"+' <div class=\"sensor-value\">'"
"+' <div class=\"sensor-label\">Kosteus</div>'"
"+' <div class=\"sensor-number\">'+d.hum+'<span class=\"sensor-unit\">%</span></div>'"
"+' </div>'"
"+' <div class=\"sensor-value\">'"
"+' <div class=\"sensor-label\">Akku</div>'"
"+' <div class=\"sensor-number\">'+d.bat+'<span class=\"sensor-unit\">%</span></div>'"
"+' </div>'"
"+' <div class=\"sensor-value\">'"
"+' <div class=\"sensor-label\">Jännite</div>'"
"+' <div class=\"sensor-number\">'+d.batMv+'<span class=\"sensor-unit\">mV</span></div>'"
"+' </div>'"
"+' </div>';}"
"html+=' <div class=\"rssi\">📶 Signaali: '+d.rssi+' dBm</div>'"
"+'</div>';});"
"document.getElementById('devices').innerHTML=html;"
"if(openPanelId){"
"const panel=document.getElementById(openPanelId);"
"if(panel){panel.classList.add('open');openSettings=panel;}}"
"}catch(error){console.error('Virhe haettaessa laitteita:',error);}}"
"setInterval(updateDevices,2000);updateDevices();"
"</script>"
"</body>"
"</html>";

#endif // WEBSERVER_H
